### ISSUE TITLE
Stream overread due to incorrect `SkeletalMesh.HasRayTracingData` flag

### ISSUE THREAD

**Issue by ScrubN** [FabianFG/CUE4Parse#101]
I have been decompiling a recent Unreal Engine 4 game for the NS with FModel and noticed that most meshes were throwing `NullReferenceException`s when trying to convert the LODModels.
![image](https://github.com/FabianFG/CUE4Parse/assets/72096833/756fae3a-7b45-4ac5-9e72-aef7bec9a156)

Upon further debugging, when comparing the stream offset to a hex editor, it seemed the reader was overreading when deserializing, in this specific case, the 2nd LOD model. From there I found the problem was being cause by the `SkeletalMesh.HasRayTracingData` flag being raised despite the mesh not having any ray tracing data.

This results in the following compatibility code interpreting bad data as, in this case, the header for a 257 length array of ray tracing data and advancing the reader beyond the start of the next LOD mesh. Removing the check seems to fix the problem entirely, leading me to believe the flag is being incorrectly raised.
https://github.com/FabianFG/CUE4Parse/blob/86d95053f04184fe7fb36ab57bf0c967221ef7d3/CUE4Parse/UE4/Assets/Exports/SkeletalMesh/FStaticLODModel.cs#L372-L375

Unfortunately this is where my debugging stops.

I am aware that FModel is using an older version of CUE4Parse, so I pulled the latest changes from CUE4Parse/master and acl/develop and the issue was still present.

**Comment by GMatrixGames** [comment]
Are you using the correct UE version. And please share the game.

**Comment by ScrubN** [comment]
Ah sorry, I am decompiling Pikmin4. I am unsure what version of UE4 it is using, how would I check?

**Comment by GMatrixGames** [comment]
https://github.com/FModel/Game-Compatibility/blob/master/VERIFIED_WORKING.md#unreal-engine-426

**Comment by Amrsatrio** [comment]
Hi, apologies for having the Versions dictionary being difficult be figure out. You can pass it through the constructor of FileProvider that has an argument with type VersionContainer, where you can specify your UE version and compatibility flags.

**Comment by ScrubN** [comment]
> https://github.com/FModel/Game-Compatibility/blob/master/VERIFIED_WORKING.md#unreal-engine-426

That indeed solves the issue, thank you for your help!

Would it be possible to link that document somewhere such as in the FModel README?
