### ISSUE TITLE
Mesh Vertex Paint Data (.umap)

### ISSUE THREAD

**Issue by Tectors** [FabianFG/CUE4Parse#105]
**"Painted Vertices" data** is missing, the data shows up in the UEFN (patched) editor once you copy a mesh, but in CUE4Parse the data isn't read.

An example of this can be seen in the S4 Lobby **(/Game/Maps/UI/Frontend_Lobby_Season4)** on latest (patched UEFN):

This mesh has vertices painted on.
![image](https://github.com/FabianFG/CUE4Parse/assets/73559984/8ac25435-f387-4aa8-847b-f832a370f280)

Once we copy it, and look in notepad, we see this data:
![image](https://github.com/FabianFG/CUE4Parse/assets/73559984/f8f2b1ee-73a0-4c82-90e9-2419fad0b671)
![image](https://github.com/FabianFG/CUE4Parse/assets/73559984/915a60fd-4b58-4e8d-b658-e1525047c9b1)

As you can see, this is the vertex data from the mesh into UE3 text data, meaning the data is present inside of the level
Let's take a look inside FModel (that utilizes CUE4Parse):

Here is the same mesh you saw above:
![image](https://github.com/FabianFG/CUE4Parse/assets/73559984/ad5438e1-e3a4-445d-9e19-1e23359a6826)

And here is the data provided:
![image](https://github.com/FabianFG/CUE4Parse/assets/73559984/25160900-ade9-4c19-aee5-575b0e7fc935)

As you can see, no painted vertices data, but it does exist

Resources that may help you:
https://github.com/EpicGames/UnrealEngine/blob/a3cb3d8fdec1fc32f071ae7d22250f33f80b21c4/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.h#L786
https://github.com/EpicGames/UnrealEngine/blob/a3cb3d8fdec1fc32f071ae7d22250f33f80b21c4/Engine/Source/Runtime/Engine/Private/Components/StaticMeshComponent.cpp#L1451

**Comment by 4sval** [comment]
![image](https://github.com/FabianFG/CUE4Parse/assets/26126862/82eb130b-9995-4f62-961e-5622c1aa6ea9)

**Comment by Tectors** [comment]
This'll produce the same data?

**Comment by KedisPL** [comment]
This still isn't fully fixed. There should be a ColorVertexData.

**Comment by 4sval** [comment]
ok, tell me more?

**Comment by KedisPL** [comment]
> ok, tell me more?

So if you have, for example, a UEFN (Patched) and you copy some mesh from a map that has it with vertex colours all the data is present (Stride, NumVerticles, ColorVertexData), but in CUE4Parse there isn't ColorVertexData only Stride and NumVerticles.

Resource that may help you:
https://github.com/EpicGames/UnrealEngine/blob/5.3/Engine/Source/Runtime/Engine/Private/Components/StaticMeshComponent.cpp#L113

**Comment by 4sval** [comment]
in CUE4Parse there's Stride, NumVertices, and Data. That's all you need to get your colors back.
Data is obviously not written in the JSON for the sake of readability.

**Comment by KedisPL** [comment]
So how can I get the data?

**Comment by KedisPL** [comment]
Never mind, I didn't see the commented lines in JsonConverters.cs
