### ISSUE TITLE
Request for a new feature : Can you please make it compatible with BINKA audio

### ISSUE THREAD

**Issue by Macflylegamerlevrai** [FabianFG/CUE4Parse#109]
Hi! I am trying to remake Garten Of BanBan but I need the audio of the game but I've looked everywhere and I found nothing to extract BINKA audio to wav or mp3 so can u please make CUE4Parse compatible with BINKA audio ? Pls

**Comment by speige** [comment]
These might help
https://gist.github.com/angelsl/5594021
http://tiberiumwars.com/greygoo/GreyGooRipper.zip
