### ISSUE TITLE
Snowbreak support needs update

### ISSUE THREAD

**Issue by ThiconZ** [FabianFG/CUE4Parse#114]
Late in 2023 Snowbreak updated and [support](https://github.com/FabianFG/CUE4Parse/commit/e1c4af637b618479c89c3c57477ac6f6c633b7b2) for it no longer works. It would be helpful to have a new game entry added for the new version of the game - which is still running on UE4.26.2.0.
Looking at the updated QuickBMS script which does work, it seems to have been a minor change. In the attached QuickBMS script the `CONVERT` function defined on line 416 is the change needed. It is called on Line 267 inside of `SET_AES_KEY_ASK` as the last action before actual operations begin.

```
callfunction CONVERT 1
```
```
startfunction CONVERT
	get TMP_NAME basename
	string TMP_NAME l TMP_NAME
	encryption md5 TMP_NAME
	encryption "" ""
	set MEMORY_FILE binary QUICKBMS_HEXHASHL
	
	encryption aes AES_KEY "" 1 32
	log MEMORY_FILE2 0 32 MEMORY_FILE
	encryption "" ""
	goto 0 MEMORY_FILE2
	getdstring AES_KEY 32 MEMORY_FILE2
endfunction
```

[unreal_tournament_4_0.4.27e_snowbreak.bms.txt](https://github.com/FabianFG/CUE4Parse/files/13983336/unreal_tournament_4_0.4.27e_snowbreak.bms.txt)

**Comment by GMatrixGames** [comment]
Known issue, if you wish to implement the changes, feel free to make a PR!
