### ISSUE TITLE
Cannot decode UTexture2D

### ISSUE THREAD

**Issue by ShadeTheIn** [FabianFG/CUE4Parse#13]
Hello, I'm trying to export a texture icon as UTexture2D, and when calling `Decode()` it throws this exception:
  `System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable 1 source, Func 2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable 1 source, Func 2 predicate)`

The exception is thrown at line 113 of `UTexture2D.cs`

And this is how I'm loading the texture:

> var texture = provider.LoadObject<UTexture2D>(@"FortniteGame/Content/UI/Foundation/Textures/Icons/Backpacks/T-Icon-Backpacks-773-Carabus-L");

                
> var image = texture.Decode();

Thank you, I hope I was able to be descriptive on my issue, and hopefully it's just me doing something wrong.

**Comment by iAmAsval** [comment]
what's the full code

**Comment by ShadeTheIn** [comment]
var provider = new DefaultFileProvider(@"C:\Program Files\Epic Games\Fortnite\FortniteGame\Content\Paks", SearchOption.TopDirectoryOnly, true);
provider.Initialize();

var guid = new FGuid("00000000000000000000000000000000");
var aes = new FAesKey("3FE5C589D219E71EE15FEB8FA9BC6B6224BB58AA826A0FA1D997D92E0D8DB23A");
provider.SubmitKey(guid, aes);
var texture = provider.LoadObject<UTexture2D>(@"/Game/Content/UI/Foundation/Textures/Icons/Backpacks/T-Icon-Backpacks-773-Carabus-L"); //error throws on this line

**Comment by ShadeTheIn** [comment]
The issue is happening again after verifying my game files, here is the full code: 

```cs
var provider = new DefaultFileProvider(@"C:\Program Files\Epic Games\Fortnite\FortniteGame\Content\Paks", SearchOption.TopDirectoryOnly, true);
                provider.Initialize();

                var guid = new FGuid("00000000000000000000000000000000");
                var aes = new FAesKey("3FE5C589D219E71EE15FEB8FA9BC6B6224BB58AA826A0FA1D997D92E0D8DB23A");
                provider.SubmitKey(guid, aes);
                var texture = provider.LoadObject<UTexture2D>(@"/Game/Content/UI/Foundation/Textures/Icons/Backpacks/T-Icon-Backpacks-773-Carabus-L"); //error throws on this line
```

**Comment by iAmAsval** [comment]
provider.LoadMappings() after submitkey

**Comment by ShadeTheIn** [comment]
the exception still gets thrown

**Comment by iAmAsval** [comment]
I just tested it and there's absolutely no issue if you do everything right
initialize the provider, submit keys, load mappings, load object

**Comment by ShadeTheIn** [comment]
Did I do everything correctly in the code I provided above? I'm really not sure what else there is to do. Is your working code different than mine?

**Comment by ShadeTheIn** [comment]
Also, you can't see it in the code snippet but as I mentioned earlier, the exception isn't thrown when the texture is loaded, it's thrown when I called the Decode method

**Comment by iAmAsval** [comment]
because you have no mappings

**Comment by ShadeTheIn** [comment]
idk man, even with loading the mappings the exception still throws:

```
            var provider = new DefaultFileProvider(@"C:\Program Files\Epic Games\Fortnite\FortniteGame\Content\Paks", SearchOption.TopDirectoryOnly, true);
            provider.Initialize();
            provider.LoadMappings();

            var guid = new FGuid("00000000000000000000000000000000");
            var aes = new FAesKey("0x3FE5C589D219E71EE15FEB8FA9BC6B6224BB58AA826A0FA1D997D92E0D8DB23A");
            provider.SubmitKey(guid, aes);
            var texture = provider.LoadObject<UTexture2D>(@"/Game/UI/Foundation/Textures/Icons/Backpacks/T-Icon-Backpacks-773-Carabus-L");
            texture.Decode();

**Comment by iAmAsval** [comment]
> provider.LoadMappings() after submitkey

...

**Comment by ShadeTheIn** [comment]
still throws even if i put it after submitkey lol

**Comment by iAmAsval** [comment]
then paste and edit https://github.com/FabianFG/CUE4Parse/blob/master/CUE4Parse.Example/Program.cs
