### ISSUE TITLE
Animation extracting seems not work on Wuthering waves

### ISSUE THREAD

**Issue by developer-ken** [FabianFG/CUE4Parse#140]
When extracting animation from Wuthering waves, https://github.com/FabianFG/CUE4Parse/blob/4e955153559be8dc156d15fc93ff8c1016d3ebfe/CUE4Parse-Conversion/Animations/AnimConverter.cs#L287 throws a exception:  
``
System.ArgumentOutOfRangeException:“Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name”
``

`skeleton.BoneCount` at https://github.com/FabianFG/CUE4Parse/blob/4e955153559be8dc156d15fc93ff8c1016d3ebfe/CUE4Parse-Conversion/Animations/AnimConverter.cs#L123 is only `2` , which seems suspicious.

I have no idea what to do now. Any help or information appreciated.

https://github.com/4sval/FModel/discussions/473

**Comment by LongerWarrior** [comment]
which Animation?

**Comment by developer-ken** [comment]
Should be reproduced by any animation under `Client/Content/Aki/Character/Role/MaleS/Lingyang/CommonAnim`.
Workaround by change [CUE4Parse\UE4\Assets\Exports\Animation\USkeleton.cs line ](https://github.com/FabianFG/CUE4Parse/blob/4e955153559be8dc156d15fc93ff8c1016d3ebfe/CUE4Parse/UE4/Assets/Exports/Animation/USkeleton.cs#L27) to:
`public int BoneCount => ReferenceSkeleton.FinalRefBoneInfo.Length;`
