### ISSUE TITLE
Does PSA files contain morph data?

### ISSUE THREAD

**Issue by developer-ken** [FabianFG/CUE4Parse#141]
By extracting psa and psk files, I succesfully reproduced an aimation outside the game. But the extracted model shows no facial expression, but in game it does.

By reading the animation json file, I see possibly related keywords under `CompressedCurveData` . Is that data extracted to the final psa file?

By reading the model json file , I found `MorphTarget` related to those expressions. Is that data extracted to the final psk file?

If some data is not extracted, is there any way I can import them into blender or something?

Working on _Wuthering Waves_ , using animations and model from `Client/Content/Aki/Character/Role/MaleS/Lingyang`.

**Comment by developer-ken** [comment]
Morph data are exported to psk files. It's blender plugins' problem not reading them.

**Comment by developer-ken** [comment]
PSK files contains morph targets, PSA files seems not. Is this the expected behavior or I missed something?

**Comment by 4sval** [comment]
PSA contains the animation data for bones and only bones
