### ISSUE TITLE
broken animation after importing from fmodel to UE 5.4 using UEformat?

### ISSUE THREAD

**Issue by M-U-X** [FabianFG/CUE4Parse#150]
[Models.zip](https://github.com/user-attachments/files/16430739/Models.zip)
using the latest UE version, Fmodel(QA) & UEformat, I exported & imported the following mesh:
Valorant: ShooterGame/Content/Characters/Vampire/S0/3P/Models/TP_Vampire_S0_Skelmesh.uasset
& the following animations:
ShooterGame/Content/Characters/_Core/3P/Anims/TP_Core_WalkN_LB.uasset
ShooterGame/Content/Characters/_Core/3P/Anims/TP_Core_WalkAddN_UB.uasset

the mesh gets imported just fine, but the animations look broken:
![image](https://github.com/user-attachments/assets/7cc15cb5-f40d-4168-b91c-47408aba7c88)
![image](https://github.com/user-attachments/assets/b45f1120-eda8-4a30-be4d-0b23aa3d919f)
![image](https://github.com/user-attachments/assets/3b14ebbc-402a-40a2-83df-dfd0d3d4e720)
model & animation files are attached,

**Comment by halfuwu** [comment]
https://github.com/halfuwu/UEFormat/issues/9

keep it here, when one of us can investigate we'll give you an answer

**Comment by M-U-X** [comment]
> [halfuwu/UEFormat#9](https://github.com/halfuwu/UEFormat/issues/9)
> 
> keep it here, when one of us can investigate we'll give you an answer

sorry didn't know which where to post since I've no idea if the issue is cue4p export related or UEformat related
