### ISSUE TITLE
Usmap version parsing bad

### ISSUE THREAD

**Issue by Hiro420** [FabianFG/CUE4Parse#172]
So I tried loading latest Usmap (from https://fortnitecentral.genxgames.gg/api/v1/mappings), same Usmap FModel uses, like this:
```csharp
var provider = new DefaultFileProvider(_gameDirectory, SearchOption.TopDirectoryOnly, true, new VersionContainer(EGame.GAME_UE5_4));
provider.MappingsContainer = new FileUsmapTypeMappingsProvider(_mapping);
```
`_mapping` being the path to mappings file.
CUE4 raises an exception: `An error occurred: Usmap has invalid version (3)`, while FModel doesn't when using the EXACT SAME usmaps.
wtf is going on?

**Comment by GMatrixGames** [comment]
Use the submodule, not the nuget package.
