### ISSUE TITLE
Cutsene questin

### ISSUE THREAD

**Issue by LievreAI** [FabianFG/CUE4Parse#3]
Can i export Cutsene?

**Comment by Amrsatrio** [comment]
Can you give us more details like the game, path, and UE version?

**Comment by LievreAI** [comment]
Game Called Sword Art Online Fatal Bullet , UE4.17

**Comment by iAmAsval** [comment]
path?

if you're actually talking about cutscenes/cinematics, that's not how it works
you can export assets used in those cutscenes if you find them
