### ISSUE TITLE
[FR] Loading UMap from old ue4 4.8.3 ver

### ISSUE THREAD

**Issue by MaverXka** [FabianFG/CUE4Parse#36]
Im trying to open umap from unreal engine 4.8.3 and i got this error:

[ERR] One or more errors occurred. (Invalid FString length '1768714054')
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

If it possible add FString support for 4.8.3

**Comment by MaverXka** [comment]
for example problem:

UMap file:

https://drive.google.com/file/d/1_f9fiTaraHeQ88KqyTEch_DjAx5Uqqgg/view?usp=sharing

**Comment by GMatrixGames** [comment]
I actually have time to look into this, do you have the full files for this? Having just a umap doesn't really help.
