### ISSUE TITLE
Publish CUE4Parse as a NuGet package

### ISSUE THREAD

**Issue by taradinoc** [FabianFG/CUE4Parse#42]
Most third-party .NET libraries are distributed as NuGet packages, which are easy for developers to discover and include in their projects. NuGet also saves consumers the trouble of configuring a special build environment in order to use one library with unusual build requirements.

Publishing CUE4Parse on NuGet would mean developers can add it to their projects with a single `PackageReference` line, or with a few clicks by searching for it in the package manager, without having to use submodules or install CMake into their PATH.

I've [modified CUE4Parse](https://github.com/FabianFG/CUE4Parse/compare/master...BanjoByTheBay:master) to build NuGet packages, which are currently [published on NuGet.org](https://www.nuget.org/packages/BanjoByTheBay.CUE4Parse/) under an "unofficial" name. I can clean that up and submit a PR, if you'd like, but the code changes are pretty small -- I think the real work will be in numbering releases and uploading them, or writing actions to do that automatically.

Also, NuGet [recommends](https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#licensing) specifying the package's license: see #39.

**Comment by GMatrixGames** [comment]
https://www.nuget.org/packages/CUE4Parse
https://www.nuget.org/packages/CUE4Parse-Conversion
https://www.nuget.org/packages/CUE4Parse-Fortnite

In future published versions, they will have a license once one is decided on, and will have an updated description

**Comment by taradinoc** [comment]
> https://www.nuget.org/packages/CUE4Parse-Fortnite

This package is unlisted, is that intentional?

**Comment by GMatrixGames** [comment]
Yes it is, as it no longer exists
