### ISSUE TITLE
Animation Curve Value Calculated Incorrectly

### ISSUE THREAD

**Issue by Tectors** [FabianFG/CUE4Parse#45]
Hello, today I decided to build the latest dev version of FModel, which includes the last modification of the curves (c6a6e8b519a30f9a3fbf8c61e0f2cead10826ae1).

I went ahead to the ROM animation that includes tons of facial curves, I then imported all the curves into Unreal Engine to get a real showcase of the curves.

Since the animation curves had a picture online from a Epic Games Documentation page, I decided I wanted to compare photos to give you a better look of what's wrong.

![image](https://user-images.githubusercontent.com/73559984/166165039-a2baa5f0-254b-4fdb-897c-7044b8592dc7.png)

**The values are not stable, they are right for one key, then the next one is just incorrect. Basically to explain as much as I know.**

## For example:

- First Key:
Value = .4
Time = .1

- Next Key:
Value = .01
Time = .133333

I think you may be able to see the problem here, the next key is not correct, the time or value is incorrect, I presume the value is incorrect because with mocap it usually updates fast with the person's face. If you want a side by side video of their animation compared to the FModel curve animation, I am able to provide you with it. 

Also to note: The implementation worked completely fine before, not in UE5 of course, but that isn't the source problem. These curves weren't working either in UE4 so we can remove the cause of the Engine version in that sense.

If you want to see the difference from before and now of the JSON files I am going to provide you with them, check below.

[Comparison.zip](https://github.com/FabianFG/CUE4Parse/files/8599797/Comparison.zip)

The values seem to differ a ton, look at them yourself. It seems like many decimals are being stripped from the value.

**Comment by Tectors** [comment]
Another image:
![image](https://user-images.githubusercontent.com/73559984/166165256-bc2bf2d9-0616-4cde-9ad5-2f5515b84112.png)

**Comment by Tectors** [comment]
Here is how a animation from the old FModel exports the curves.
https://streamable.com/gnopsc

**Comment by iAmAsval** [comment]
> The implementation worked completely fine before

It worked before what exactly?

> not in UE5 of course ... These curves weren't working either in UE4

What worked then?


The anim implementation has not been edited for at least 6 months
I can see the differences, they are all related to the Key Data Adapter but they all seem to act like they should, unlike before (see [Tangents Weight not being set to 0](https://github.com/EpicGames/UnrealEngine/blob/ue5-main/Engine/Source/Runtime/Engine/Private/Curves/RichCurve.cpp#L2007-L2015))

**Comment by Tectors** [comment]
> > The implementation worked completely fine before
> 
> It worked before what exactly?
> 
> > not in UE5 of course ... These curves weren't working either in UE4
> 
> What worked then?
> 
> The anim implementation has not been edited for at least 6 months I can see the differences, they are all related to the Key Data Adapter but they all seem to act like they should, unlike before (see [Tangents Weight not being set to 0](https://github.com/EpicGames/UnrealEngine/blob/ue5-main/Engine/Source/Runtime/Engine/Private/Curves/RichCurve.cpp#L2007-L2015))

Yes, indeed the curves were right and able to be used in Unreal Engine completely raw with no modifications as you can see in streamable videos I provided.

I was suggesting that the implementation was possibly changed and could of altered the curves, look below as it shows one of the differences between before and after.
![image](https://user-images.githubusercontent.com/73559984/167237308-e7848814-ffd6-450c-adfa-39f31e3a279e.png)

Yes, the tangent weight is one of the differences but our main focus is the value, the value matters the most in curves.

Now, a few days ago I found that **19.30** combined with the match of [4.2.1.0](https://github.com/iAmAsval/FModel/releases/tag/4.2.1.0) (FModel, whatever the CUE4Parse version may be) worked completely fine in usage of Unreal Engine. Using latest completely threw off the curves into a undefined object.

I may correct myself, it is the game version that changed how the curves are that CUE4Parse can't read right completely to the full-extent. Because trying in the latest version of Fortnite (currently 20.30) with that exact FModel and CUE4Parse version didn't work.

**Comment by iAmAsval** [comment]
Did you ever use the data provided by `CompressedCurveData` because it looks like `ConvertCurves` has never been valid when compared to `RawCurveData` which is now gone, thus the beginning of this problem

**Comment by Tectors** [comment]
> Did you ever use the data provided by `CompressedCurveData` because it looks like `ConvertCurves` has never been valid when compared to `RawCurveData` which is now gone, thus the beginning of this problem

Provide a file that I can test, if you don't mind.
