### ISSUE TITLE
How can I read/deserialize AssetRegistry into json?

### ISSUE THREAD

**Issue by Civ01** [FabianFG/CUE4Parse#46]

**Comment by iAmAsval** [comment]
just like any other package

**Comment by Civ01** [comment]
This links to a completely different repo

**Comment by iAmAsval** [comment]
things are the same

**Comment by Civ01** [comment]
Not really. It wast obvious from the short example that you need to explicitly mount provider.

**Comment by iAmAsval** [comment]
what?
