### ISSUE TITLE
Discrepancy between GLTF and PSK Mesh Export

### ISSUE THREAD

**Issue by halfuwu** [FabianFG/CUE4Parse#50]
It seems that there's a difference between the vertices & edges between meshes exported as GLTF and PSK.

![image](https://user-images.githubusercontent.com/69497698/173200934-ffe54419-4a37-47c5-bdd2-2125e68b7565.png)
![image](https://user-images.githubusercontent.com/69497698/173200952-7ac412fe-8a0e-4a28-9430-8cf9e86279a3.png) 
![image](https://user-images.githubusercontent.com/69497698/173200958-45adb375-857e-48d8-ba42-287f0db434da.png)
The meshes look pretty much identical in terms of where vertices are yet they differ in vertex and edge count.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/69497698/173201086-16490acb-8eea-4d15-a374-ca60cea0e719.gif)
It seems like there are some double vertices that aren't carrying over from gltf to psk. Is this a limitation of psk or is there some other reason for this? Would be super useful to get the psk data near identical to gltf so that morph target data would be usable on them.

**Comment by floxay** [comment]
Have you looked at this?
https://github.com/FabianFG/CUE4Parse/blob/370b35d1e0e981501d5f18c574cb55e20ac3000d/CUE4Parse-Conversion/Meshes/PSK/CVertexShare.cs#L72

<details>
<summary>PS</summary>
Double verts don't play nice btw.
</details>

**Comment by halfuwu** [comment]
Yup just looked at that! Seems like if you just always run the code inside of that if statement and import into blender using your vtxnorms build, everything still looks fine and has the correct amount of vertices and edges, thanks for much for the help!! :D
