### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by BIDOUNI** [FabianFG/CUE4Parse#53]
Hey, can you do a tutorial for build it please, I have a lot of cmake errors 

![image](https://user-images.githubusercontent.com/61655182/183247332-beb4145a-e6a6-454c-9983-e3601d0be190.png)

**Comment by 4sval** [comment]
https://github.com/FabianFG/CUE4Parse#requirements

https://github.com/FabianFG/CUE4Parse#building-cue4parse

**Comment by BIDOUNI** [comment]
Already do that, I have these errors when i try to build

**Comment by MinshuG** [comment]
Have you installed C++ workload in visual studio?
