### ISSUE TITLE
IO store support?

### ISSUE THREAD

**Issue by Kein** [FabianFG/CUE4Parse#55]
I see some references to IOstore in the code, but can't figure out if it is fully supported and if so, is there a way to read IOstore packages. Right now, filelist from `DefaultFileProvider` returns me only what inside the PAKs, which is half of the content.
The rest is inside IOstore packages. Can these be read to get filelist and object's exports?

**Comment by GMatrixGames** [comment]
I/O store is fully supported, as Fortnite uses it.

**Comment by Kein** [comment]
Looks like there has been servere changes for IO store as of `ue5-main`

**Comment by GMatrixGames** [comment]
How recent?

**Comment by Kein** [comment]
I've tested `ue5-main` about a month ago but today UE5.1 Preview became available so it is not relevant anymore much. I dont see any changes in the IOstore header, but tghe logic itself has some things completely rewritten so the packaging/serialization logic probably differs now as well.

**Comment by Kein** [comment]
That's odd, I've built ir5-main in august. For some reason, C4P only reads PAKs here:
https://www.dropbox.com/s/qc03qedf5vm2olu/Paks.7z?dl=1
