### ISSUE TITLE
Tower of Fantasy 2.2 error

### ISSUE THREAD

**Issue by Hungibungi** [FabianFG/CUE4Parse#56]
Hi!

Since I saw ToF is in EGame.cs, I thought I will put this here.
With the 2.2 patch the .pak files got changed yet again, whenever you try to open any uasset file you get this error:
Invalid uasset magic: 0x{Tag:X8} != 0x{PACKAGE_FILE_TAG:X8}, because Tag != PACKAGE_FILE_TAG && Tag != PACKAGE_FILE_TAG_SWAPPED.
Global is only using the 2.0 CN files so it currently works, but when they decide to swap to the 2.2 client it will be an issue over there as well. I tried to use the old method of getting the offset, but now it doesn't work anymore as it's not just simply xoring the numbers with an offset (at least I think it's not).
What I found weird is that umodel works just fine even with 2.2.

~PerkyJerky
![image](https://user-images.githubusercontent.com/92867468/189475706-9855b3b3-86ad-476b-88d6-54620f242976.png)
![image](https://user-images.githubusercontent.com/92867468/189476041-d427e1c3-e1d7-45f1-8298-7980b018cfc7.png)
![image](https://user-images.githubusercontent.com/92867468/189475730-35215848-4aae-4734-b836-50a7184ae28e.png)

**Comment by Hungibungi** [comment]
Just a quick update:
The offset is the same, so that's not the issue. I got bamboozled, but after extracting the uasset files with quickbms the same offset works. Something else is broken, as it can't even extract the raw uasset files, it just throws out some gibberish.

**Comment by GMatrixGames** [comment]
Do you have the AES key for this update?

**Comment by Hungibungi** [comment]
0x2F5D80E5AF41285E090F711CC462B963275C428648CB3C19FC1CC85ADA3326C2

**Comment by Amrsatrio** [comment]
Should be fixed now, you can close this issue if there are no more breaking issues with 2.2. Thank you for your patience.
![image](https://user-images.githubusercontent.com/20662640/194484352-7547a378-fdf1-4b6e-952b-c0f6e416d66c.png)

**Comment by Hungibungi** [comment]
Seems like everything is working, thank you for the fix!

**Comment by Amrsatrio** [comment]
Make sure to pull changes again because I've made some fixes to keep compatibility with other UE4-5 games and older versions of ToF.
