### ISSUE TITLE
[Bug] Wide/Unicode FNames break parsing of simplified UCAS uassets

### ISSUE THREAD

**Issue by Kein** [FabianFG/CUE4Parse#62]
Test example: [Paks.zip](https://github.com/FabianFG/CUE4Parse/files/10049838/Paks.zip)
Packed with IOstore on 4.27.2.
`MyAcotrClas.uasset` asset inside UCAS has 2 props
`TestProp:   Geschäft`       `80 08 00 47 00 65 00 73 00 63 00 68 00 E4 00 66 00 74 00`
`TestProp2: АвывыАжкх` `80 09 10 04 32 04 4B 04 32 04 4B 04 10 04 36 04 3A 04 45 04`

**Comment by GMatrixGames** [comment]
If you can supply the global files, that would help.
