### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506) When calling Package GetExports()

### ISSUE THREAD

**Issue by ptubini** [FabianFG/CUE4Parse#67]
Not sure why but depending of the package this error is happening

**Comment by GMatrixGames** [comment]
Need more information.
Game name
UE version

**Comment by ptubini** [comment]
@GMatrixGames 

Game Name: MultiVersus
UE Version: 4.26.0.0

**Comment by 4sval** [comment]
package?

**Comment by ptubini** [comment]
dotnet add package CUE4Parse --version 1.0.4


Package: multiversus/content/panda_main/prematch/prematch_builtdata.uasset

**Comment by GMatrixGames** [comment]
don't open builtdata files

**Comment by ptubini** [comment]
@GMatrixGames Is there a way that I can filter it? Just so I don't need to filter using the actual name

**Comment by 4sval** [comment]
filter using actual names

**Comment by ptubini** [comment]
Thanks for the help @GMatrixGames @4sval

**Comment by ptubini** [comment]
It's also happening with non builtdata files, follow an example below:

multiversus/content/wwiseaudio/localized/italian/media/3a/48/977804481.uasset

Is anything that we can do to prevent fatal errors like that @GMatrixGames @4sval ?

**Comment by 4sval** [comment]
fix your code

**Comment by 4sval** [comment]
fr, there's nothing you can do about it
this error happens when dealing with unsafe stuff
even a try-catch doesn't work for it
