### ISSUE TITLE
Can't read the files from pak file

### ISSUE THREAD

**Issue by KiKiHUN** [FabianFG/CUE4Parse#68]
I tried your example, and i searched around  your code, but can't find out why it can't find the files inside the pak.
Maybe i missed some settings?
The game is built on 4.24.3, so i used GAME_UE4_24.
No encription on the files.
[
![image](https://user-images.githubusercontent.com/49228599/211531475-ea3aaae6-61dc-4f00-b875-d33450e9e528.png)
](url)

**Comment by 4sval** [comment]
no encryption doesn't mean you have to skip the SubmitKey method
use an empty key

**Comment by KiKiHUN** [comment]
Like so?
Same thing, file count=0.
```
  byte[] emptyArray = new byte[32];
  provider.SubmitKey(new FGuid(), new FAesKey(emptyArray)); 
```

**Comment by 4sval** [comment]
0x0000000000000000000000000000000000000000000000000000000000000000

**Comment by KiKiHUN** [comment]
Don't get it. Still null the aes key.
![image](https://user-images.githubusercontent.com/49228599/211539269-d7ad3fd5-8dce-4a94-bb5b-12d1b4ec6cec.png)

**Comment by KiKiHUN** [comment]
Oh nevermind. Just found the mount() function. Works now. Thanks for your help.

**Comment by KiKiHUN** [comment]
Nah, still can't find how to load the files.
I can see every file in one .pak after mounting that unloaded .pak.(still unloaded, but can see the files)
But after that, can't do anything with them.
Followed the example, gave a real, working path, but it always says that "there is no game file with the path ..." 
I'm soo lost with this.
