### ISSUE TITLE
CUE4Parse.Example does not compile

### ISSUE THREAD

**Issue by sk6868** [FabianFG/CUE4Parse#91]
Please update the [CUE4Parse.Example](https://github.com/FabianFG/CUE4Parse/tree/master/CUE4Parse.Example) code so it compiles correctly.  Furthermore, the wiki link referring to 'more detailed explanation' is just a link to itself, so it's not very helpful.

**Comment by halfuwu** [comment]
https://github.com/FabianFG/CUE4Parse/commit/4cbba24887d7728173a78a8d0f2b87bcdd2b3efc
