### ISSUE TITLE
Parsing fails on Asteria_Terrain.umap

### ISSUE THREAD

**Issue by donCalculator** [FabianFG/CUE4Parse#93]
CUE4Parse\CUE4Parse\UE4\Assets\Exports\UObject.cs
...
`if (!Flags.HasFlag(EObjectFlags.RF_ClassDefaultObject) && Ar.ReadBoolean() && Ar.Position + 16 <= validPos)`
...
Ar.ReadBoolean() is causing this error:
```
CUE4Parse.UE4.Exceptions.ParserException: Invalid bool value (1230987625)
FAssetArchive Info: FortniteGame/Content/Athena/Asteria/Maps/Asteria_Terrain.umap Pos 7751917 Length 149233731
```

**Comment by 4sval** [comment]
you don't even have the correct mappings wdym
