### ISSUE TITLE
S.T.A.L.K.E.R. 2

### ISSUE THREAD

**Issue by ponaromixxx** [FabianFG/CUE4Parse#94]
Hello, you answered me earlier in the Fmodel topic, but can you tell me what kind of Mappings.usmap file from Stalker2 is? And are there any options for unpacking pak and utoc, ucas files for S.T.A.L.K.E.R. 2.

**Comment by 4sval** [comment]
https://github.com/OutTheShade/UnrealMappingsDumper

**Comment by GMatrixGames** [comment]
https://github.com/OutTheShade/Unreal-Mappings-Archive/blob/main/S.T.A.L.K.E.R.%202/Pre-Alpha/Mappings.usmap
