### ISSUE TITLE
Potionomics - Unhandled exception of type 'System.ExecutionEngineException' in Unknown module.

### ISSUE THREAD

**Issue by Release** [FabianFG/CUE4Parse#97]
On "Potionomics/Content/Blueprints/BP_PlayerController.uasset" FModel crashed with error "Unhandled exception of type 'System.ExecutionEngineException' in Unknown module."

Code to reproduce the error:
```
var exports = Provider.LoadAllObjects(fullPath); // fullPath = "Potionomics/Content/Blueprints/BP_PlayerController.uasset"

foreach (var obj in exports) // <= An error occurs in the third step.
{
    System.Diagnostics.Debug.WriteLine(obj.ToString());
}
```

In debugging, after an error occurs, Visual Studio does not display the call stack.
In manual debugging, the error occurs at this line (...\CUE4Parse\CUE4Parse\UE4\Assets\AbstractUePackage.cs):
`public` IEnumerable<UObject> GetExports() => ExportsLazy.Select(x => x.Value);

FModel uses CUE4Parse version 1.0.7.0, I updated to the latest 1.0.9.0, but the error persists.
I can’t find a place on my own to localize and at least get around the cause.

Problematic asset in the attachment:
[Potionomics.zip](https://github.com/FabianFG/CUE4Parse/files/12087928/Potionomics.zip)

**Comment by C0reTheAlpaca** [comment]
Same issue for me with the game Predecessor.
Here are some assets that trigger it:

- "WBP_ReplayHUDSwitcher.uasset",
- "HUD_Game.uasset",
- "BP_PredPlayerController_Menu.uasset",
- "BP_PredPlayerController_Game_Default.uasset",
- "BP_PredPlayerController_Game_Practice.uasset",
- "BP_PredPlayerController_Game_Tutorial.uasset"

**Comment by yretenai** [comment]
Potionomics (UE4.24) seems to have ByteProperty set to 8 bytes when in a TMap. 

Predecessor (UE5.1) likely needs TMapOverrides, but the game uses EasyAntiCheat so dumping them is risky.
